FROM migrate/migrate

COPY ./migrations ./migrations
COPY ./scripts/migrate-entrypoint.sh /usr/local/bin/migrate-entrypoint.sh

RUN chmod +x /usr/local/bin/migrate-entrypoint.sh

ENV POSTGRES_USER=username
ENV POSTGRES_PASSWORD=passwd
ENV POSTGRES_HOST=localhost
ENV POSTGRES_PORT=5432
ENV POSTGRES_DB=students

WORKDIR .
ENTRYPOINT ["/usr/local/bin/migrate-entrypoint.sh"]
CMD ["up"]