FROM python:3.8-slim-buster

WORKDIR /app

ENV GRPC_HOST=::
ENV GRPC_PORT=8080
ENV POSTGRES_HOST=localhost
ENV POSTGRES_PORT=5432
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password123123123
ENV POSTGRES_DB=students
EXPOSE 8080

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt


COPY . .

CMD ["python3", "server.py"]
