"""init

Revision ID: f158d5283b27
Revises: 
Create Date: 2023-04-12 22:52:25.065041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f158d5283b27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('create schema alemb')
    op.create_table('t_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='alemb',
    comment='Users'
    )
    op.create_index(op.f('ix_alemb_t_user_email'), 't_user', ['email'], unique=True, schema='alemb')
    op.create_index(op.f('ix_alemb_t_user_full_name'), 't_user', ['full_name'], unique=False, schema='alemb')
    op.create_index(op.f('ix_alemb_t_user_id'), 't_user', ['id'], unique=False, schema='alemb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alemb_t_user_id'), table_name='t_user', schema='alemb')
    op.drop_index(op.f('ix_alemb_t_user_full_name'), table_name='t_user', schema='alemb')
    op.drop_index(op.f('ix_alemb_t_user_email'), table_name='t_user', schema='alemb')
    op.drop_table('t_user', schema='alemb')
    op.execute('drop schema alemb')
    # ### end Alembic commands ###
